<?php

namespace package\application;


/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/5/20
 * Time: 11:51
 */

/**
 * WebSocketServer 服务器类
 * Class WebSocketServer
 * @package package\application
 */
class WebSocketServer extends \cn\eunionz\core\Server
{

    public function onMessage($server, $frame, $cfg)
    {
        parent::onMessage($server, $frame, $cfg); // TODO: Change the autogenerated stub
    }

}